/*
 * This source file was generated by the Gradle 'init' task
 */
package org.william.tasks;

import org.junit.jupiter.api.Test;
import org.william.tasks.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
